# Generated by Django 4.1.7 on 2023-03-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
