# Generated by Django 4.1.7 on 2023-03-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_genres_titles', '0002_rename_categorie_category_remove_title_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
