# Generated by Django 4.1.7 on 2023-03-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_genres_titles', '0003_remove_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-id']},
        ),
    ]
