# Generated by Django 4.1.7 on 2023-03-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_comments', '0004_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
