# Generated by Django 4.1.7 on 2023-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_comments', '0006_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
