# Generated by Django 4.1.7 on 2023-03-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_comments', '0010_alter_comment_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
